apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      k8s.web.com/name: db
  template:
    metadata:
      labels:
        k8s.web.com/name: db
    spec:
      containers:
      - name: db
        image: mysql:5.7.30
        resources:
          limits:
            memory: 1Gi
            cpu: "2"
        ports:
        - containerPort: 3306
          name: db
          protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: data
          - mountPath: /etc/mysql/conf.d/mysql_custom.cnf
            name: configurations
            subPath: mysql_custom.cnf
          - mountPath: /docker-entrypoint-initdb.d/init.sql
            name: configurations
            subPath: init.sql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-root-password
          - name: MYSQL_USER
            value: admin
          - name: MYSQL_DATABASE
            value: dockerweb
      initContainers:
      - command:
        - rm
        - -fr
        - /var/lib/mysql/lost+found
        image: busybox:1.31.1
        imagePullPolicy: IfNotPresent
        name: remove-lost-found
        resources:
           requests:
             cpu: 100m
             memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: mysql-cm
        name: configurations
      - name: data
        persistentVolumeClaim:
          claimName: db
      
